apiVersion: v1
kind: ConfigMap
metadata:
  name: streamflix-config
data:
  # Variáveis de ambiente para a API e o Worker
  DATABASE_URL: "postgresql://admin:admin@postgres-service:5432/streamflix"
  RABBIT_HOST: "rabbitmq-service"
  RABBIT_PORT: "5672"
  RABBIT_USER: "admin"
  RABBIT_PASS: "admin"